---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator 
summary: 'Der Trident-Operator ermöglicht es Ihnen, die Art und Weise, wie Astra Trident installiert wird, mithilfe der Attribute im anzupassen `TridentOrchestrator` Spez.' 
---
= Anpassung der Trident Operator-Implementierung
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Der Trident-Operator bietet Ihnen die Möglichkeit, die Installation von Astra Trident mithilfe der Attribute im anzupassen `TridentOrchestrator` Spez.

Die Liste der Attribute finden Sie in der folgenden Tabelle:

[cols="3"]
|===
| Parameter | Beschreibung | Standard 


| `namespace` | Namespace für die Installation von Astra Trident in | „Standard“ 


| `debug` | Aktivieren Sie das Debugging für Astra Trident | Falsch 


| `IPv6` | Installieren Sie Astra Trident über IPv6 | Falsch 


| `k8sTimeout` | Zeitüberschreitung für Kubernetes-Betrieb | 30 Sek. 


| `silenceAutosupport` | Schicken Sie AutoSupport Bundles nicht automatisch an NetApp | Falsch 


| `enableNodePrep` | Automatische Verwaltung der Abhängigkeiten von Workers Node (*BETA*) | Falsch 


| `autosupportImage` | Das Container-Image für AutoSupport Telemetrie | „netapp/Trident-Autosupport:21.04.0“ 


| `autosupportProxy` | Die Adresse/der Port eines Proxys zum Senden von AutoSupport Telemetrie | "http://proxy.example.com:8888"[] 


| `uninstall` | Eine Flagge, die zum Deinstallieren von Astra Trident verwendet wird | Falsch 


| `logFormat` | Astra Trident Protokollformat zur Verwendung [Text, json] | „Text“ 


| `tridentImage` | Astra Trident-Image zu installieren | „netapp/Trident:21.04“ 


| `imageRegistry` | Pfad zur internen Registrierung des Formats
`<registry FQDN>[:port][/subpath]` | „K8s.gcr.io/sig-Speicherung (k8s 1.17+) oder quay.io/k8scsi“ 


| `kubeletDir` | Pfad zum kubelet-Verzeichnis auf dem Host | „/var/lib/kubelet“ 


| `wipeout` | Eine Liste mit zu löschenden Ressourcen, um Astra Trident vollständig zu entfernen |  


| `imagePullSecrets` | Secrets, um Bilder aus einer internen Registrierung zu ziehen |  
|===

IMPORTANT: `spec.namespace` Ist in angegeben `TridentOrchestrator` Um zu kennzeichnen, in welchem Namespace Astra Trident installiert ist. Dieser Parameter *kann nicht aktualisiert werden, nachdem Astra Trident installiert wurde*. Der Versuch, dies zu tun, verursacht den Status von `TridentOrchestrator` Zu ändern `Failed`. Astra Trident ist nicht für die Migration auf Namespaces vorgesehen.


NOTE: Die automatische Workers Node Prep ist eine *Beta-Funktion*, die nur in nicht-Produktionsumgebungen verwendet werden soll.

Sie können die oben genannten Attribute beim Definieren verwenden `TridentOrchestrator` Um die Installation anzupassen. Hier ein Beispiel:

[listing]
----
$ cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  tridentImage: netapp/trident:21.04.0
  imagePullSecrets:
  - thisisasecret
----
Wenn Sie die Installation über das hinaus anpassen möchten `TridentOrchestrator` Argumente erlauben, sollten Sie erwägen, zu verwenden `tridentctl` So generieren Sie benutzerdefinierte YAML-Manifeste, die Sie nach Bedarf ändern können.
